<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../common.props" />
	<Import Project="../../configureawait.props" />

	<ItemGroup>
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="SharpGrip.FluentValidation.AutoValidation.Mvc" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Hospital.Fw.Domain\Hospital.Fw.Domain.csproj" />
	</ItemGroup>
</Project>