<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../../common.props" />
	<Import Project="../../configureawait.props" />
	<ItemGroup>
	  <None Remove="Entities\CreationPinyinEnableCodeAuditedEntity.cs~RF87f1f0.TMP" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hospital.Fw.Application.Contract\Hospital.Fw.Application.Contract.csproj" />
		<ProjectReference Include="..\Hospital.Fw.Domain.Shared\Hospital.Fw.Domain.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="SqlSugarCore" />
	</ItemGroup>
</Project>
