<Project Sdk="Microsoft.NET.Sdk.Web">

	<Import Project="../../common.test.props" />

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\module\Hospital.Fw.BackgroundJobs\Hospital.Fw.BackgroundJobs.csproj" />
	  <ProjectReference Include="..\..\module\Hospital.Fw.Interceptor.Logging\Hospital.Fw.Interceptor.Logging.csproj" />
	  <ProjectReference Include="..\..\module\Hospital.Fw.Interceptor.Sequence\Hospital.Fw.Interceptor.Sequence.csproj" />
	  <ProjectReference Include="..\..\module\Hospital.Fw.Mo.Logging\Hospital.Fw.Mo.Logging.csproj" />
	  <ProjectReference Include="..\..\src\Hospital.Fw.HttpApi\Hospital.Fw.HttpApi.csproj" />
	  <ProjectReference Include="..\..\src\Hospital.Fw.SqlSugarCore\Hospital.Fw.SqlSugarCore.csproj" />
	  <PackageReference Include="Rougamo.Fody" />
	</ItemGroup>

</Project>
