<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="../../../common.props" />
	<Import Project="../../../configureawait.props" />
	<ItemGroup>
	  <ProjectReference Include="..\..\..\src\Hospital.Fw.SqlSugarCore\Hospital.Fw.SqlSugarCore.csproj" />
	  <ProjectReference Include="..\Hospital.Fw.Automatic.Api.Domain\Hospital.Fw.Automatic.Api.Domain.csproj" />
	</ItemGroup>
</Project>